language: node_js
sudo: true

node_js:
  - '11.9'
  - '10.15'

cache:
  - npm
  - yarn

before_install:
  - git submodule update --init --remote --recursive

install:
  - travis_retry make ci-install

script:
  - yarn run tsc
  # - yarn run test
