language: node_js
sudo: true

node_js:
  - '11.9'
  - '10.15'

cache:
  - npm
  - yarn

before_install:
  - git submodule update --init --remote --recursive
  - npm install -g lerna

install:
  - travis_retry make ci-install

script:
  - lerna run tsc
  - yarn run test utils formatters
